#!/bin/bash
#ai/pythonscripts
alias vimgit='python3 $HOME/linuxcommands/ai/pythonscripts/vimgit.py'
alias brsoverview='~/linuxcommands/ai/pythonscripts/brsoverview.py'

#Other scripts, 
alias gll='source ~/linuxcommands/scripts/generategithublink.sh'

# Personal
alias s='source ~/sourcing_script.sh; source ~/.bashrc'
alias lsl='ls -ltr'

alias q='fold -w 80 -s ~/tmp/a | less'
alias qaa='fold -w 50 -s ~/tmp/aa | less'
alias qaaa='fold -w 50 -s ~/tmp/aaa | less'

# Git aliases,
alias gitlog='git log --pretty=oneline --graph'
alias gitkraken='gitkraken -p .'
alias gits='git status'
alias gitc='bash /home/ngara/linuxcommands/ai/bashscripts/gitautocommit.sh'
alias gitb='git branch --show-current'
alias gitinc='git fetch && git log ..origin/main'
# alias gitinc='git log main..origin/main'
alias gitout='git log remotes/origin/"$(git symbolic-ref --short HEAD)".."$(git symbolic-ref --short HEAD)"'
alias gitpush='git push -u origin main'
alias gitdiffwithmain='git diff main.."$(git symbolic-ref --short HEAD)"'
alias gitdiffwithmaster='git diff master.."$(git symbolic-ref --short HEAD)"'
alias syncrepos='python /home/ngara/linuxcommands/ai/pythonscripts/syncgitrepos.py; echo "debbit"'
alias listtests='python /home/ngara/linuxcommands/ai/pythonscripts/listtests.py'



function gitout { 
branch=${1:}
# git log origin/main..main ;
git log remotes/origin/"$(git symbolic-ref --short HEAD)".."$(git symbolic-ref --short HEAD)"

}

function gitr {
git remote -v; 

# generate weblink for the repo,
# Change "origin	git@github.com:username/reponame.git (fetch)" to "https://github.com/username/reponame"

git remote -v  |grep fetch | \
 sed 's^.git (fetch)^^' | \
sed 's^origin.*git@^https://^' | \
 sed 's^com:^com/^'
}
# function gitinc { git fetch && git log main..origin/main ;}

alias r='reset'

alias gg='~/linuxcommands/scripts/grepquicknotes.sh'
function abb() {
find $HOME -maxdepth 4 -type f -name "*abbreviations*" |xargs grep "$1"
}

function h() {
history |grep $1
grep $1 ~/n/frequentlyusedcommands.txt
}

alias vimt='vim *.tex'

alias gitwho='echo -n "local.user.email:"; git config --local user.email; echo "" ; echo -n "local.user.name:"; git config --local user.name ; echo ""; echo -n "global.user.email:"; git config --global user.email; echo -n "global.user.name:"; git config --global user.name'

alias gitloglocalonlybranches='git log --graph --oneline --branches --not --remotes=*'

# git branch piped to grep
alias gitbg='git branch --all | grep'


alias n='cd $HOME/n'
alias nu='cd $HOME/nu'

alias soundtest='speaker-test --nperiods 10 --nloops 1'


alias brsoverview='python3 ~/linuxcommands/ai/pythonscripts/brsoverview.py'
