#!/bin/bash
# Personal
alias s='source ~/sourcing_script.sh; source ~/.bashrc'
alias lsl='ls -ltr'

alias q='fold -w 80 -s ~/tmp/a | less'
alias qaa='fold -w 50 -s ~/tmp/aa | less'
alias qaaa='fold -w 50 -s ~/tmp/aaa | less'
alias b='cd ..'
alias bb='cd ../..'
alias bbb='cd ../../..'
alias bbbb='cd ../../../..'
alias bbbbb='cd ../../../../../'
alias 4b='cd ../../../../'
alias 5b='cd ../../../../../'
alias 6b='cd ../../../../../../'
alias 7b='cd ../../../../../../../'

# Type "ls -tr". Then do cd3 to cd in to the 3rd director.
alias cd1='cd `ls -dtr */ |head -1 |tail -1`'
alias cd2='cd `ls -dtr */ |head -2 |tail -1`'
alias cd3='cd `ls -dtr */ |head -3 |tail -1`'
alias cd4='cd `ls -dtr */ |head -4 |tail -1`'
alias cd5='cd `ls -dtr */ |head -5 |tail -1`'
alias cd6='cd `ls -dtr */ |head -6 |tail -1`'

# Type "ls -tr". Then do cd3 to cd in to the 3rd last director.
alias 1cd='cd `ls -dtr */  |tail -1 |head -1`'
alias 2cd='cd `ls -dtr */  |tail -2 |head -1`'
alias 3cd='cd `ls -dtr */  |tail -3 |head -1`'
alias 4cd='cd `ls -dtr */  |tail -4 |head -1`'
alias 5cd='cd `ls -dtr */  |tail -5 |head -1`'
alias 6cd='cd `ls -dtr */  |tail -6 |head -1`'
alias 7cd='cd `ls -dtr */  |tail -7 |head -1`'
alias 8cd='cd `ls -dtr */  |tail -8 |head -1`'


# Git aliases,
alias gitlog='git log --pretty=oneline --graph'
alias gitkraken='gitkraken -p .'
alias gits='git status'
alias gitc='/home/ngara/linuxcommands/ai/bashscripts/gitautocommit.sh'
alias gitb='git branch --show-current'
alias gitinc='git fetch && git log ..origin/main'
# alias gitinc='git log main..origin/main'
alias gitout='git log remotes/origin/"$(git symbolic-ref --short HEAD)".."$(git symbolic-ref --short HEAD)"'
alias gitpush='git push -u origin main'
alias gitdiffwithmain='git diff main.."$(git symbolic-ref --short HEAD)"'
alias gitdiffwithmaster='git diff master.."$(git symbolic-ref --short HEAD)"'
alias syncrepos='python /home/ngara/linuxcommands/ai/pythonscripts/syncgitrepos.py'
alias listtests='python /home/ngara/linuxcommands/ai/pythonscripts/listtests.py'



function gitout { 
branch=${1:}
# git log origin/main..main ;
git log remotes/origin/"$(git symbolic-ref --short HEAD)".."$(git symbolic-ref --short HEAD)"

}

function gitr {
git remote -v; 

# generate weblink for the repo,
# Change "origin	git@github.com:username/reponame.git (fetch)" to "https://github.com/username/reponame"

git remote -v  |grep fetch | \
 sed 's^.git (fetch)^^' | \
sed 's^origin.*git@^https://^' | \
 sed 's^com:^com/^'
}
# function gitinc { git fetch && git log main..origin/main ;}

# Speedy aliases,
alias ff='source ~/linuxcommands/scripts/findwithname.sh'
alias vimff='~/linuxcommands/scripts/vimfindfirstoccurance.sh'
alias cdff='source ~/linuxcommands/scripts/cdfindfirstoccurance.sh' #Its important to source this as there is a 'cd' command inside of this script.
alias cddff='source ~/linuxcommands/scripts/cddfindfirstoccurance.sh' #Its important to source this as there is a 'cd' command inside of this script.
alias catff='source ~/linuxcommands/scripts/catfindfirstoccurance.sh' #Its important to source this as there is a 'cd' command inside of this script.
alias fp='source ~/linuxcommands/scripts/fullpath.sh'
alias fullpath='source ~/linuxcommands/scripts/fullpath.sh'


alias ff1='~/linuxcommands/scripts/findwithnamemaxdepth.sh 1'
alias ff2='~/linuxcommands/scripts/findwithnamemaxdepth.sh 2'
alias ff3='~/linuxcommands/scripts/findwithnamemaxdepth.sh 3'
alias ff4='~/linuxcommands/scripts/findwithnamemaxdepth.sh 4'
alias ff5='~/linuxcommands/scripts/findwithnamemaxdepth.sh 5'
alias ff6='~/linuxcommands/scripts/findwithnamemaxdepth.sh 6'
alias ff7='~/linuxcommands/scripts/findwithnamemaxdepth.sh 7'

alias findallfiles='find . -type f'
alias findalldirs='find . -type d'

alias r='reset'

alias gg='~/linuxcommands/scripts/grepquicknotes.sh'
function abb() {
find $HOME -maxdepth 4 -type f -name "*abbreviations*" |xargs grep "$1"
}

function h() {
history |grep $1
grep $1 ~/n/frequentlyusedcommands.txt
}

alias vimt='vim *.tex'

alias gitwho='echo -n "local.user.email:"; git config --local user.email; echo "" ; echo -n "local.user.name:"; git config --local user.name ; echo ""; echo -n "global.user.email:"; git config --global user.email; echo -n "global.user.name:"; git config --global user.name'

alias gitloglocalonlybranches='git log --graph --oneline --branches --not --remotes=*'

# git branch piped to grep
alias gitbg='git branch --all | grep'


alias n='cd $HOME/n'
alias nu='cd $HOME/nu'

alias soundtest='speaker-test --nperiods 10 --nloops 1'

alias gll='source ~/linuxcommands/scripts/generategithublink.sh'

alias brsoverview='python3 ~/linuxcommands/ai/pythonscripts/brsoverview.py'
